# Generated by Django 2.1.1 on 2018-09-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180914_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='staff',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='admin',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='account',
            name='active',
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
